version: '3.7'
services:

  mysql:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER:           wp
      MYSQL_PASSWORD:       "${MYSQL_PASSWORD}"

      MYSQL_DATABASE:       wp
      MYSQL_ROOT_PASSWORD:  "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - "${DATA_DIR}/mysql/data:/var/lib/mysql"

  wp:
    image: wordpress:5.1.1-php7.2-apache
    restart: always
    ports:
      - "127.0.0.1:8080:80"
    environment:
      WORDPRESS_DB_HOST:      mysql
      WORDPRESS_DB_NAME:      wp

      WORDPRESS_DB_USER:      wp
      WORDPRESS_DB_PASSWORD:  "${MYSQL_PASSWORD}"

